/* 
1.
1) 테이블
2) 외래키(FK)
3) 널(NULL)

2-2
1) 문자셋(CharacterSet)
2) 문자셋(CharSet)

2-3.
1) VARCHAR2(N)
2) CHAR(N)

2-4.
1) 제약조건
2) 기본키
3) 외래키

2-5.
1) 무결성
2) 무결성
3) 무결성

2-6.
1) Unique
2) Not Null
3) INDEX
*/


--8p-1
SELECT DEPTNO, TRUNC(AVG(SAL))AS AVG_SAL ,MAX(SAL) AS MAX_SAL,MIN(SAL) AS MIN_SAL, COUNT(EMPNO) AS CNT
FROM EMP
GROUP BY DEPTNO;

--8p-2
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(JOB)>=3;

--8p-3
SELECT  HIREDATE_YEAR,DEPTNO, COUNT(*) AS COUNT
FROM (
    SELECT DEPTNO, EXTRACT(YEAR FROM HIREDATE) AS HIREDATE_YEAR
     FROM EMP
)
GROUP BY DEPTNO , HIREDATE_YEAR;


--9p-4
SELECT 
CASE 
WHEN COMM IS NOT NULL THEN 'Y'
ELSE 'N' END AS "추가수당 여부", 
COUNT(*) AS "인원 수" 
FROM EMP 
GROUP BY 
CASE 
WHEN COMM IS NOT NULL THEN 'Y'
ELSE 'N' END;
    
--9p-5
SELECT DEPTNO, EXTRACT(YEAR FROM HIREDATE) AS "HIRE_YEAR", COUNT(*) AS "CNT", 
MAX(SAL),SUM(SAL),AVG(SAL)
FROM EMP 
GROUP BY ROLLUP (DEPTNO, EXTRACT(YEAR FROM HIREDATE))
ORDER BY DEPTNO;


--10p-1
--ORACLE
SELECT A.DEPTNO, B.DNAME, A.EMPNO, A.ENAME, A.SAL
FROM EMP A, DEPT B
WHERE A.DEPTNO  = B.DEPTNO 
AND SAL>2000;

--표준
SELECT A.DEPTNO, DNAME, EMPNO, ENAME, SAL
FROM EMP A INNER JOIN DEPT B
ON A.DEPTNO  = B.DEPTNO 
WHERE SAL>2000;

--10p-2
SELECT DEPTNO, DNAME, TRUNC(AVG(SAL)), MAX(SAL), MIN(SAL), COUNT(EMPNO)
FROM EMP NATURAL JOIN DEPT
GROUP BY DEPTNO, DNAME ;


--11p-3
SELECT A.DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL
FROM EMP A RIGHT JOIN DEPT B
ON A.DEPTNO = B.DEPTNO ;


--11p-4
SELECT d.DEPTNO, d.DNAME , e1.EMPNO , e1.ENAME, e1.MGR, e1.SAL, e1.DEPTNO, s.LOSAL, s.HISAL, s.GRADE, e1.MGR AS MGR_EMPNO, e2.ENAME AS MGR_NAME
FROM EMP e1 LEFT JOIN EMP e2 ON e1.MGR = e2.EMPNO
LEFT JOIN SALGRADE s ON e1.SAL >= s.LOSAL AND e1.SAL <= s.HISAL
RIGHT JOIN DEPT d ON e1.DEPTNO = d.DEPTNO
ORDER BY 1, 3;

--12P. -1
SELECT e.job,  e.empno, e.ename, e.sal,  d.deptno, d.dname
FROM emp e
JOIN dept d ON e.deptno = d.deptno
WHERE e.job = (SELECT job FROM emp WHERE ename = 'ALLEN');


--12P. -2
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (SELECT AVG(SAL) FROM EMP);

--13p-3
SELECT e.EMPNO, e.ENAME, e.JOB, e.DEPTNO, d.DNAME, d.LOC
FROM EMP e ,DEPT d
WHERE e.DEPTNO = d.DEPTNO
AND e.DEPTNO = 10
AND e.JOB NOT IN
(SELECT JOB FROM EMP WHERE DEPTNO = 30);


--13p-4
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE SAL > (SELECT MAX(SAL)
FROM EMP
WHERE JOB IN ('SALESMAN')
GROUP BY JOB);


--13p-5
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E 
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE SAL > ALL(SELECT SAL FROM EMP WHERE JOB IN ('SALESMAN'));
